=== xsonorg/tangyuan2/tangyuan-base/src/main/java/org/xson/tangyuan/schema/component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://xson.org/schema/tangyuan/component" targetNamespace="http://xson.org/schema/tangyuan/component" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="app-placeholder">
		<xs:complexType>
			<xs:attribute name="resource" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="app-property">
		<xs:complexType>
			<xs:attribute name="resource" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="thread-pool">
		<xs:complexType>
			<xs:attribute name="resource" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="httpclient">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="resource" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="config-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="component">
		<xs:complexType>
			<xs:attribute name="resource" type="xs:string" use="required"/>
			<xs:attribute name="type" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sql"/>
						<xs:enumeration value="java"/>
						<xs:enumeration value="mongo"/>
						<xs:enumeration value="mq"/>
						<xs:enumeration value="es"/>
						<xs:enumeration value="hbase"/>
						<xs:enumeration value="timer"/>
						<xs:enumeration value="rpc"/>
						<xs:enumeration value="web"/>
						<xs:enumeration value="cache"/>
						<xs:enumeration value="validate"/>
						<xs:enumeration value="aop"/>
						<xs:enumeration value="hive"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="system-aop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="pointcut" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="startup-before"/>
						<xs:enumeration value="startup-after"/>
						<xs:enumeration value="shutdown-before"/>
						<xs:enumeration value="shutdown-after"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="tangyuan-component">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="app-placeholder"/>
					<xs:element ref="app-property"/>
					<xs:element ref="config-property"/>
					<xs:element ref="thread-pool"/>
					<xs:element ref="httpclient"/>
					<xs:element ref="system-aop"/>
					<xs:element ref="component"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xsonorg/tangyuan2/tangyuan-base/src/main/resources/tangyuan3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tangyuan-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://xson.org/schema/tangyuan/1.2.2/component.xsd">

	<app-placeholder resource="app-placeholder.properties"/>
	<!-- 
	<app-placeholder resource="file:///C:/Users/Lenovo/Desktop/temp/app-placeholder.properties"/>
	 -->
	
	<app-property resource="app-property.inix"/>

	<config-property name="maxWaitTimeForShutDown" value="60"/>
	<config-property name="allServiceReturnXCO" value="true"/>
	<!-- <config-property name="jdkProxy" value="true"/> -->
	<config-property name="shutdownInNewThread" value="true"/>
	
	<!-- <trace-config resource="trace-config.properties"/> -->
	
	<!-- 
	<system-aop pointcut="startup-before" class="org.xson.tangyuan2.demo.ssaop.StartupBefore" />
	<system-aop pointcut="startup-after" class="org.xson.tangyuan2.demo.ssaop.StartupAfter" />
	<system-aop pointcut="shutdown-before" class="org.xson.tangyuan2.demo.ssaop.ShutdownBefore" />
	<system-aop pointcut="shutdown-after" class="org.xson.tangyuan2.demo.ssaop.ShutdownAfter" />
	 -->
	
	<httpclient id="client1" resource="properties/http.client.properties"/>
	
	<!-- <manager resource="properties/http.client.properties"/> 迁移到组件中-->
<!-- 

	<component resource="component-manager.xml" type="manager" />

	<component resource="sql-component.xml" type="sql" />
	<component resource="timer-component.xml" type="timer" />
	<component resource="cache-component.xml" type="cache" />
	<component resource="aop-component.xml" type="aop" />
	<component resource="validate-component.xml" type="validate" />
	<component resource="java-component.xml" type="java" />
	<component resource="rpc-component.xml" type="rpc" />
	<component resource="component-mongo.xml" type="mongo" />
	<component resource="component-mq.xml" type="mq" />
	<component resource="sql-component.xml" type="sql" />
	<component resource="component-hbase.xml" type="hbase" />
	<component resource="component-es.xml" type="es" />
	<component resource="sql-component.xml" type="sql" />
	<component resource="rpc-component.xml" type="rpc" />
 	
 	<component resource="component-mongo.xml" type="mongo" />
 	<component resource="sql-component.xml" type="sql" />
 	
 	<component resource="java-component.xml" type="java" />
 	<component resource="cache-component.xml" type="cache" />
 	<component resource="component-mongo.xml" type="mongo" />	
 	<component resource="component-timer.xml" type="timer" />
 	
 	<component resource="sql-component.xml" type="sql" />
 	<component resource="java-component.xml" type="java" />
 	<component resource="component-aop.xml" type="aop" />
 	<component resource="component-timer.xml" type="timer" />
 	 
 	<component resource="sql-component.xml" type="sql" />
	
	<component resource="component-timer.xml" type="timer" />
	
	<component resource="component-timer-ha.xml" type="timer"/>
	<component resource="java-component.xml" type="java" />
	<component resource="cache-component.xml" type="cache" />
	<component resource="sql-component2.xml" type="sql" />
	
	<component resource="component-tools.xml" type="tools" />
	<component resource="component-hive.xml" type="hive" />
	<component resource="java-component.xml" type="java" />
	
	<component resource="sql-component-oracle.xml" type="sql" />
 -->
 	<component resource="component-tools.xml" type="tools" />
	<component resource="component-rpc-balance.xml" type="rpc" />
	
	<component resource="component-sql.xml" type="sql" />
	
	
	<!-- 插件: 混合服务插件 -->
	<plugin resource="service/service-if-sql.xml" />
	<plugin resource="service/service-if-sql.xml" />
	
</tangyuan-component>
