=== xsonorg/tangyuan2/tangyuan-base/src/main/java/org/xson/tangyuan/aop/schema/component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://xson.org/schema/tangyuan/aop/component" targetNamespace="http://xson.org/schema/tangyuan/aop/component" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="aop-component">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="before"/>
					<xs:element ref="after"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="before">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="include"/>
					<xs:element name="exclude"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="exec" type="xs:string" use="required"/>
			<xs:attribute name="order" type="xs:int" use="optional"/>
			<xs:attribute name="mode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SYNC"/>
						<xs:enumeration value="ASYNC"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="after">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="include"/>
					<xs:element name="exclude"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="exec" type="xs:string" use="required"/>
			<xs:attribute name="order" type="xs:int" use="optional"/>
			<xs:attribute name="mode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SYNC"/>
						<xs:enumeration value="ASYNC"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="condition">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SUCCESS"/>
						<xs:enumeration value="EXCEPTION"/>
						<xs:enumeration value="ALL"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xsonorg/tangyuan2/tangyuan-base/src/main/resources/component-aop.xml
<?xml version="1.0" encoding="UTF-8"?>
<aop-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://xson.org/schema/tangyuan/aop/1.2.2/component.xsd">
	
	<before exec="abc" mode="EXTEND" order="" cloneArg="true/false">
		<include type="GROUP/NAME/SERVICE_TYPE">*</include>
		<include type="GROUP/NAME">*</include>
	</before>
	
	<before exec="a/b" mode="EXTEND" order="">
		<include>abc*</include>
	</before>
	
	<after exec="c/d" mode="EXTEND" order="" condition="ALL" cloneArg="true/false">
		<include></include>
	</after>
	
</aop-component>
